#PS_PATH = -I../../fdps/src/
#PS_PATH = -I../fdps/
PS_PATH = -I../../../fdps/src/

use_k_computer = yes
#use_xc30_naoj = yes

ifeq ($(use_k_computer),yes)
CXX = time mpiFCCpx
CXXFLAGS = -Kfast
CXXFLAGS += -DPARTICLE_SIMULATOR_THREAD_PARALLEL -Kopenmp
CXXFLAGS += -DPARTICLE_SIMULATOR_MPI_PARALLEL
CXXFLAGS += -x32
CXXFLAGS += -Xg
CXXFLAGS += -DFAST_ALL_TO_ALL_FOR_K
CXXFLAGS += -DFAST_WALK_K
CXXFLAGS += -std=c++11
#CXXFLAGS += -NRtrap
CXXFLAGS += -Nfjcex
CXXFLAGS += -Krestp=all
CXXFLAGS += -DINTRINSIC_K
endif

ifeq ($(use_xc30_naoj),yes)
CXX = time CC
CXXFLAGS = -O3 
CXXFLAGS += -Wall
CXXFLAGS += -march=core-avx2
CXXFLAGS += -ffast-math -funroll-loops
CXXFLAGS += -DPARTICLE_SIMULATOR_THREAD_PARALLEL -fopenmp
CXXFLAGS += -DPARTICLE_SIMULATOR_MPI_PARALLEL
CXXFLAGS += -std=c++11
CXXFLAGS += -DINTRINSIC_X86
endif

#CXXFLAGS += -DDEBUG_PRINT_PLANET
#CXXFLAGS += -DSANITY_CHECK_REALLOCATABLE_ARRAY
#CXXFLAGS += -DPARTICLE_SIMULATOR_TWO_DIMENSION
#CXXFLAGS += -DUSE_STD_SORT
#CXXFLAGS += -DFORDEBUG
#CXXFLAGS += -DFREE_MALLOC_TREE 
#CXXFLAGS += -DPARTICLE_SIMULATOR_BARRIER_FOR_PROFILE

SRC = main_kepler.cc hard.hpp class.hpp force.hpp io.hpp kepler.hpp phantomquad_for_p3t_x86.hpp domain.hpp

all:profile.out
#all:original.out
#all:p3t_kepler_quad_nomerge_phantom_fix_engchk.out
#all:p3t_kepler_quad_nomerge_phantom_fix.out
#all:p3t_kepler_quad_merge_phantom_fix.out
#all:p3t_kepler_quad_nomerge_phantom_fix_64bit.out
#all:p3t_kepler_quad_merge_phantom_fix_64bit_cont.out
#all:p3t_kepler_quad_nomerge_phantom_fix_engchk.out
#all:p3t_kepler_quad_nomerge_phantom_fix_64bit_engchk_cont.out
#all:debug.out
#all:debug_cont.out
#all:debug2.out
#all:force_chk_quad.out
#all:force_chk_mono.out
#all:p3t_kepler_quad_nomerge_phantom_fix_64bit_engchk.out



force_chk_quad.out:$(SRC) Makefile
	$(CXX) -DP3T_64BIT -DFORCE_CHECK  -DUSE_QUAD -DDIV_FIX -DMERGE $(PS_PATH) $(CXXFLAGS) -o $@ $<

force_chk_mono.out:$(SRC) Makefile
	$(CXX) -DP3T_64BIT -DFORCE_CHECK  -DDIV_FIX  -DMERGE $(PS_PATH) $(CXXFLAGS) -o $@ $<

debug.out:$(SRC) Makefile
	$(CXX) -DUSE_QUAD -DDIV_FIX -DMERGE $(PS_PATH) $(CXXFLAGS) -o $@ $<

debug_cont.out:$(SRC) Makefile
	$(CXX) -DCALC_HARD_ENERGY  -DUSE_QUAD -DDIV_FIX -DMERGE -DREAD_FILE $(PS_PATH) $(CXXFLAGS) -o $@ $<

p3t_kepler_quad_merge_phantom_fix.out:$(SRC) Makefile
	$(CXX)  -DUSE_QUAD -DDIV_FIX -DMERGE $(PS_PATH) $(CXXFLAGS) -o $@ $<

original.out:$(SRC) Makefile
	$(CXX)  -DUSE_QUAD -DDIV_FIX -DMERGE -DORIGINAL $(PS_PATH) $(CXXFLAGS) -o $@ $<

p3t_kepler_quad_merge_phantom_fix_cont.out:$(SRC) Makefile
	$(CXX)  -DUSE_QUAD -DDIV_FIX -DMERGE -DREAD_FILE $(PS_PATH) $(CXXFLAGS) -o $@ $<

p3t_kepler_quad_merge_phantom_fix_64bit_cont.out:$(SRC) Makefile
	$(CXX)  -DP3T_64BIT -DUSE_QUAD -DDIV_FIX -DMERGE -DREAD_FILE $(PS_PATH) $(CXXFLAGS) -o $@ $<

p3t_kepler_quad_nomerge_phantom_fix.out:$(SRC) Makefile
	$(CXX)  -DUSE_QUAD -DDIV_FIX $(PS_PATH) $(CXXFLAGS) -o $@ $<

p3t_kepler_quad_nomerge_phantom_fix_64bit_engchk.out:$(SRC) Makefile
	$(CXX)  -DUSE_QUAD -DDIV_FIX -DP3T_64BIT -DENERGY_CHECK $(PS_PATH) $(CXXFLAGS) -o $@ $<

p3t_kepler_quad_nomerge_phantom_fix_engchk.out:$(SRC) Makefile
	$(CXX)  -DUSE_QUAD -DDIV_FIX -DENERGY_CHECK $(PS_PATH) $(CXXFLAGS) -o $@ $<

p3t_kepler_quad_nomerge_phantom_fix_64bit.out:$(SRC) Makefile
	$(CXX)  -DUSE_QUAD -DDIV_FIX -DPARTICLE_SIMULATOR_ALL_64BIT_PRECISION -DP3T_64BIT $(PS_PATH) $(CXXFLAGS) -o $@ $<

p3t_kepler_quad_nomerge_phantom_fix_64bit_engchk_cont.out:$(SRC) Makefile
	$(CXX)  -DUSE_QUAD -DDIV_FIX -DENERGY_CHECK -DPARTICLE_SIMULATOR_ALL_64BIT_PRECISION -DP3T_64BIT -DREAD_FILE $(PS_PATH) $(CXXFLAGS) -o $@ $<

clean:
	rm *.out
cleanall:
	rm *.out *.hpp~ *.cc~ *.h~
